# Generated by Django 2.1.2 on 2018-10-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_faculty',
            new_name='is_farmer',
        ),
    ]
