# Generated by Django 2.1.2 on 2018-10-28 15:27

import AuthUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0002_auto_20181027_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=AuthUser.models.image_upload_path),
        ),
    ]
