# Generated by Django 2.1.2 on 2018-10-30 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0003_auto_20181029_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CNF', 'Confirmed'), ('PCK', 'Packed'), ('SIP', 'Shipped'), ('DEL', 'Delivered')], default='CNF', max_length=20)),
                ('paymentOption', models.CharField(choices=[('COD', 'Cash On Delivery'), ('NB', 'Net Banking'), ('PTM', 'Paytm'), ('CDC', 'Credit/Debit Card')], default='COD', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='Items.Item')),
            ],
        ),
    ]
