# Generated by Django 2.1.2 on 2018-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paymentOption',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Net Banking', 'Net Banking'), ('Paytm', 'Paytm'), ('Credit/Debit Card', 'Credit/Debit Card')], default='COD', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='CNF', max_length=20),
        ),
    ]
