# Generated by Django 2.1.2 on 2018-10-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20181029_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
