# Generated by Django 2.1.2 on 2018-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.FloatField(default=0.0),
        ),
    ]
