# Generated by Django 2.1.2 on 2018-10-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_auto_20181027_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='location',
            new_name='longitude',
        ),
    ]
