# Generated by Django 2.1.2 on 2018-10-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0003_auto_20181027_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
