# Generated by Django 2.1.2 on 2018-10-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0004_auto_20181027_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
