# Generated by Django 2.1.2 on 2018-10-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0005_auto_20181027_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
