# Generated by Django 2.1.2 on 2018-10-28 16:16

import Farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0006_auto_20181027_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farmImage',
            field=models.ImageField(default='default_avatar.png', upload_to=Farm.models.image_upload_path),
        ),
    ]
