# Generated by Django 2.1.2 on 2018-10-28 16:17

import Farm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0007_farm_farmimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farmImage',
            field=models.ImageField(default='farm.png', upload_to=Farm.models.image_upload_path),
        ),
    ]
