apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: {{ .Values.angular.service.port }}
      targetPort: {{ .Values.angular.service.targetPort }}
