# Generated by Django 2.1.2 on 2018-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('WL', 'Water Level'), ('TS', 'Turbidity Sensor'), ('Temp', 'Temperature'), ('SM', 'Soil Moisture'), ('HDT', 'Humidity'), ('Act', 'Actuator')], default='Temp', max_length=20),
        ),
    ]
