# Generated by Django 2.1.2 on 2018-10-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0003_auto_20181027_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='max_value',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='min_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(default=70.0),
        ),
    ]
