# Generated by Django 2.1.2 on 2018-10-27 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0004_auto_20181027_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
