# Generated by Django 2.1.2 on 2018-10-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0005_sensordata_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='location',
            new_name='longitude',
        ),
    ]
