# Generated by Django 2.1.2 on 2018-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0006_auto_20181027_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Turbidity Sensor', 'Turbidity Sensor'), ('Temperature', 'Temperature'), ('Soil Moisture', 'Soil Moisture'), ('Humidity', 'Humidity'), ('Actuator', 'Actuator')], default='Temp', max_length=20),
        ),
    ]
