# Generated by Django 2.1.2 on 2018-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0007_auto_20181031_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Turbidity Sensor', 'Turbidity Sensor'), ('Temperature', 'Temperature'), ('Soil Moisture', 'Soil Moisture'), ('Humidity', 'Humidity'), ('Actuator', 'Actuator')], default='Temperature', max_length=20),
        ),
    ]
