# Generated by Django 2.1.2 on 2018-11-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0008_auto_20181101_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('Water Level', 'Water Level'), ('Turbidity', 'Turbidity'), ('Temperature', 'Temperature'), ('Soil Moisture', 'Soil Moisture'), ('Humidity', 'Humidity'), ('Actuator', 'Actuator')], default='Temperature', max_length=20),
        ),
    ]
