# Generated by Django 2.1.2 on 2018-10-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0001_initial'),
        ('Crop_Type', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crops',
            new_name='Crop',
        ),
    ]
