# Generated by Django 2.1.2 on 2018-10-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0004_auto_20181027_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='location',
            new_name='longitude',
        ),
    ]
