# Generated by Django 2.1.2 on 2018-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crop_Type', '0007_auto_20181031_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(choices=[('Kharif crops', 'Kharif crops'), ('Rabi Crops', 'Rabi Crops'), ('Zaid Crop', 'Zaid Crop'), ('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Pulses', 'Pulses'), ('Sugarcane', 'Sugarcane'), ('Cotton', 'Cotton'), ('Groundnut', 'Groundnut'), ('Tea', 'Tea'), ('Coffee', 'Coffee')], default='Pulses', max_length=20),
        ),
    ]
